"""empty message

Revision ID: 072f847d2bf0
Revises: 
Create Date: 2022-05-18 10:28:32.368447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '072f847d2bf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_car',
    sa.Column('number_plate', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('gear', sa.String(), nullable=False),
    sa.Column('no_of_cars', sa.Integer(), nullable=False),
    sa.Column('logbook_number', sa.String(), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('engine', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('fuel', sa.String(), nullable=False),
    sa.Column('drive_type', sa.String(), nullable=False),
    sa.Column('mileage', sa.String(), nullable=False),
    sa.Column('engine_size', sa.String(), nullable=False),
    sa.Column('steering', sa.String(), nullable=False),
    sa.Column('min_engcc', sa.String(), nullable=False),
    sa.Column('max_engcc', sa.String(), nullable=False),
    sa.Column('colour', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('number_plate'),
    sa.UniqueConstraint('logbook_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('add_car')
    # ### end Alembic commands ###
