"""empty message

Revision ID: 20a82f6a17af
Revises: 
Create Date: 2022-06-06 22:03:03.654152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20a82f6a17af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart_table',
    sa.Column('number_plate', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('cart_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['number_plate'], ['add_car.number_plate'], ),
    sa.ForeignKeyConstraint(['username'], ['customer_registration.username'], ),
    sa.PrimaryKeyConstraint('cart_id'),
    sa.UniqueConstraint('number_plate')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart_table')
    # ### end Alembic commands ###
