"""empty message

Revision ID: 29d3294f5f2a
Revises: 6bc728e2497e
Create Date: 2022-06-18 15:21:18.696916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d3294f5f2a'
down_revision = '6bc728e2497e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_appointment', sa.Column('problem', sa.String(), nullable=True))
    op.add_column('book_appointment', sa.Column('charges', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'book_appointment', ['appointment_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book_appointment', type_='unique')
    op.drop_column('book_appointment', 'charges')
    op.drop_column('book_appointment', 'problem')
    # ### end Alembic commands ###
