"""empty message

Revision ID: 6bc728e2497e
Revises: 
Create Date: 2022-06-17 18:34:48.317650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bc728e2497e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_appointment',
    sa.Column('appointment_id', sa.String(), nullable=False),
    sa.Column('number_plate', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['customer_registration.username'], ),
    sa.PrimaryKeyConstraint('appointment_id'),
    sa.UniqueConstraint('appointment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_appointment')
    # ### end Alembic commands ###
