"""empty message

Revision ID: f8d80b09ce9a
Revises: 29d3294f5f2a
Create Date: 2022-06-18 17:13:08.803675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8d80b09ce9a'
down_revision = '29d3294f5f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_appointment', sa.Column('appointment_state', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('book_appointment', 'appointment_state')
    # ### end Alembic commands ###
